before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    use_buildx: true
    image_templates:
    - "ghcr.io/schaermu/github-judge-bot:latest"
    - "ghcr.io/schaermu/github-judge-bot:{{ .Tag }}"
    - "ghcr.io/schaermu/github-judge-bot:v{{ .Major }}"
    - "ghcr.io/schaermu/github-judge-bot:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/amd64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
