version: 2.1
workflows:
  main:
    jobs:
      - build
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    parallelism: 2
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: go mod download

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Run tests
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- -coverprofile=coverage.txt  -race -covermode=atomic $PACKAGE_NAMES

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
  release:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout      
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: true
      - run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
      - run: curl -sL https://git.io/goreleaser | bash