version: 2.1
workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            go test -race -coverprofile=coverage.out -covermode=atomic ./..
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /tmp/test-reports
  release:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash